"""Initial migration

Revision ID: e5e0dd7acb25
Revises: 
Create Date: 2026-08-22 00:08:31.428849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e0dd7acb25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('experiment_type', sa.String(length=64), nullable=False),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ml_ready_dataset_id', sa.Integer(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('best_model_id', sa.Integer(), nullable=True),
    sa.Column('best_metric', sa.String(length=64), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_model_id'], ['trained_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ml_ready_dataset_id'], ['ml_ready_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_best_model_id'), 'experiments', ['best_model_id'], unique=False)
    op.create_index(op.f('ix_experiments_dataset_id'), 'experiments', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_index(op.f('ix_experiments_ml_ready_dataset_id'), 'experiments', ['ml_ready_dataset_id'], unique=False)
    op.create_index(op.f('ix_experiments_owner_id'), 'experiments', ['owner_id'], unique=False)
    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=128), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=512), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('validation_rows', sa.Integer(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trained_models_experiment_id'), 'trained_models', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_trained_models_id'), 'trained_models', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('num_rows', sa.Integer(), nullable=False),
    sa.Column('num_columns', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('trained_model_id', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('primary_metric', sa.String(length=64), nullable=True),
    sa.Column('primary_metric_value', sa.Float(), nullable=True),
    sa.Column('averaging_strategy', sa.String(length=64), nullable=True),
    sa.Column('evaluation_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluations_experiment_id'), 'model_evaluations', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_id'), 'model_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_trained_model_id'), 'model_evaluations', ['trained_model_id'], unique=False)
    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('trained_model_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_records_experiment_id'), 'prediction_records', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_prediction_records_id'), 'prediction_records', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_records_trained_model_id'), 'prediction_records', ['trained_model_id'], unique=False)
    op.create_table('cleaned_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('original_file_path', sa.String(length=512), nullable=False),
    sa.Column('cleaned_file_path', sa.String(length=512), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=False),
    sa.Column('rows_after', sa.Integer(), nullable=False),
    sa.Column('columns_before', sa.Integer(), nullable=False),
    sa.Column('columns_after', sa.Integer(), nullable=False),
    sa.Column('missing_values_handled', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('cleaning_status', sa.String(length=50), nullable=False),
    sa.Column('cleaning_operations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaned_datasets_dataset_id'), 'cleaned_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_cleaned_datasets_id'), 'cleaned_datasets', ['id'], unique=False)
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_dataset_id'), 'data_quality_reports', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_data_quality_reports_id'), 'data_quality_reports', ['id'], unique=False)
    op.create_table('dataset_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_profiles_dataset_id'), 'dataset_profiles', ['dataset_id'], unique=True)
    op.create_index(op.f('ix_dataset_profiles_id'), 'dataset_profiles', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('trained_model_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_dataset_id'), 'reports', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_reports_experiment_id'), 'reports', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_owner_id'), 'reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reports_trained_model_id'), 'reports', ['trained_model_id'], unique=False)
    op.create_table('engineered_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('cleaned_dataset_id', sa.Integer(), nullable=True),
    sa.Column('original_file_path', sa.String(length=512), nullable=False),
    sa.Column('engineered_file_path', sa.String(length=512), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=False),
    sa.Column('rows_after', sa.Integer(), nullable=False),
    sa.Column('columns_before', sa.Integer(), nullable=False),
    sa.Column('columns_after', sa.Integer(), nullable=False),
    sa.Column('features_added', sa.Integer(), nullable=False),
    sa.Column('features_removed', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('feature_engineering_operations', sa.JSON(), nullable=False),
    sa.Column('engineering_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cleaned_dataset_id'], ['cleaned_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineered_datasets_cleaned_dataset_id'), 'engineered_datasets', ['cleaned_dataset_id'], unique=False)
    op.create_index(op.f('ix_engineered_datasets_dataset_id'), 'engineered_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_engineered_datasets_id'), 'engineered_datasets', ['id'], unique=False)
    op.create_table('ml_ready_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('engineered_dataset_id', sa.Integer(), nullable=True),
    sa.Column('cleaned_dataset_id', sa.Integer(), nullable=True),
    sa.Column('source_dataset_type', sa.String(length=50), nullable=False),
    sa.Column('source_file_path', sa.String(length=512), nullable=False),
    sa.Column('ml_ready_file_path', sa.String(length=512), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=False),
    sa.Column('rows_after', sa.Integer(), nullable=False),
    sa.Column('train_rows', sa.Integer(), nullable=False),
    sa.Column('test_rows', sa.Integer(), nullable=False),
    sa.Column('original_feature_count', sa.Integer(), nullable=False),
    sa.Column('processed_feature_count', sa.Integer(), nullable=False),
    sa.Column('numeric_columns', sa.JSON(), nullable=False),
    sa.Column('categorical_columns', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('preprocessing_operations', sa.JSON(), nullable=False),
    sa.Column('preprocessor_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cleaned_dataset_id'], ['cleaned_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engineered_dataset_id'], ['engineered_datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ml_ready_file_path')
    )
    op.create_index(op.f('ix_ml_ready_datasets_cleaned_dataset_id'), 'ml_ready_datasets', ['cleaned_dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_ready_datasets_dataset_id'), 'ml_ready_datasets', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_ready_datasets_engineered_dataset_id'), 'ml_ready_datasets', ['engineered_dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_ready_datasets_id'), 'ml_ready_datasets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_ready_datasets_id'), table_name='ml_ready_datasets')
    op.drop_index(op.f('ix_ml_ready_datasets_engineered_dataset_id'), table_name='ml_ready_datasets')
    op.drop_index(op.f('ix_ml_ready_datasets_dataset_id'), table_name='ml_ready_datasets')
    op.drop_index(op.f('ix_ml_ready_datasets_cleaned_dataset_id'), table_name='ml_ready_datasets')
    op.drop_table('ml_ready_datasets')
    op.drop_index(op.f('ix_engineered_datasets_id'), table_name='engineered_datasets')
    op.drop_index(op.f('ix_engineered_datasets_dataset_id'), table_name='engineered_datasets')
    op.drop_index(op.f('ix_engineered_datasets_cleaned_dataset_id'), table_name='engineered_datasets')
    op.drop_table('engineered_datasets')
    op.drop_index(op.f('ix_reports_trained_model_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_owner_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_experiment_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_dataset_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_dataset_profiles_id'), table_name='dataset_profiles')
    op.drop_index(op.f('ix_dataset_profiles_dataset_id'), table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    op.drop_index(op.f('ix_data_quality_reports_id'), table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_dataset_id'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    op.drop_index(op.f('ix_cleaned_datasets_id'), table_name='cleaned_datasets')
    op.drop_index(op.f('ix_cleaned_datasets_dataset_id'), table_name='cleaned_datasets')
    op.drop_table('cleaned_datasets')
    op.drop_index(op.f('ix_prediction_records_trained_model_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_experiment_id'), table_name='prediction_records')
    op.drop_table('prediction_records')
    op.drop_index(op.f('ix_model_evaluations_trained_model_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_experiment_id'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trained_models_id'), table_name='trained_models')
    op.drop_index(op.f('ix_trained_models_experiment_id'), table_name='trained_models')
    op.drop_table('trained_models')
    op.drop_index(op.f('ix_experiments_owner_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_ml_ready_dataset_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_dataset_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_best_model_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
